global using System.Collections;
global using System.Text;
global using System.Xml;
global using System.Xml.Linq;
global using Moq;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using JsonFormatting = Newtonsoft.Json.Formatting;
global using StringWriter = Gucu112.CSharp.Automation.Helpers.Models.StringWriter;
global using XDeclaration = Gucu112.CSharp.Automation.Helpers.Models.XDeclaration;
