# Simple workflow for deploying static content to GitHub Pages
name: documentation-deploy

on:
  push:
    branches: [ "master", "experimental" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x'
      - name: Install docfx
        run: dotnet tool update -g docfx
      - name: Create artifact
        run: docfx docfx.json
      - name: Upload artifact
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .site
