# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build & Test Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build -c Release --no-restore
    - name: Publish solution
      run: dotnet publish -c Release --no-build --no-restore
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: |
          Common/Helpers.Tests/**/
          PlaywrightXunit*/**/
          Utilities/**/

  test:

    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
            - Common/Helpers.Tests
            - PlaywrightXunitParallel

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-build
        path: dist/
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.x'
    - name: Test solution
      run: dotnet test ./dist/${{ matrix.project }} --verbosity normal --filter "Category\!=Google"
